// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/build-viewer-url.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var APP_URL = "https://audio-annotation.lovable.app";
var build_viewer_url_default = defineTool({
  name: "build_viewer_url",
  title: "Build read-only viewer URL",
  description: "Build a shareable read-only Audio Annotator URL that opens an audio file with a prebuilt analysis JSON. The generated URL opens the app in read-only mode.",
  inputSchema: {
    audioUrl: z.string().url().describe("Public HTTPS URL to an audio file (mp3, wav, etc.)."),
    analysisUrl: z.string().url().optional().describe("Optional public HTTPS URL to an analysis JSON file.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ audioUrl, analysisUrl }) => {
    const params = new URLSearchParams();
    params.set("audio", audioUrl);
    if (analysisUrl) params.set("analysis", analysisUrl);
    const url = `${APP_URL}/?${params.toString()}`;
    return {
      content: [{ type: "text", text: url }],
      structuredContent: { url }
    };
  }
});

// src/lib/mcp/tools/fetch-analysis-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var fetch_analysis_summary_default = defineTool2({
  name: "fetch_analysis_summary",
  title: "Fetch analysis summary",
  description: "Fetch an Audio Annotator analysis JSON from a public URL and return a compact summary: duration, section count, section labels with timings, and detected VCU groups.",
  inputSchema: {
    analysisUrl: z2.string().url().describe("Public HTTPS URL to an analysis JSON file.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ analysisUrl }) => {
    try {
      const res = await fetch(analysisUrl);
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `Failed to fetch: HTTP ${res.status}` }],
          isError: true
        };
      }
      const data = await res.json();
      const sections = Array.isArray(data?.sections) ? data.sections : [];
      const vcus = Array.isArray(data?.vcus) ? data.vcus : [];
      const summary = {
        version: data?.version ?? null,
        duration: data?.duration ?? null,
        sectionCount: sections.length,
        sections: sections.map((s) => ({
          id: s.id,
          label: s.label ?? "",
          start: s.start,
          end: s.end,
          bars: s.bars ?? null
        })),
        vcuCount: vcus.length,
        vcus: vcus.map((v) => ({
          label: v.label ?? "",
          sectionIds: v.sectionIds ?? []
        }))
      };
      return {
        content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
        structuredContent: summary
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Error: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-demo.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var DEMO_AUDIO = "https://raw.githubusercontent.com/BigBez/audio-annotator/main/public/Analyses/beautiful-mistakes.mp3";
var DEMO_ANALYSIS = "https://raw.githubusercontent.com/BigBez/audio-annotator/main/public/Analyses/beautiful-mistakes.json";
var get_demo_default = defineTool3({
  name: "get_demo",
  title: "Get demo analysis links",
  description: "Return the built-in demo audio URL, demo analysis JSON URL, and a ready-to-open read-only viewer URL for the bundled 'Beautiful Mistakes' example.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const viewerUrl = `https://audio-annotation.lovable.app/?audio=${encodeURIComponent(
      DEMO_AUDIO
    )}&analysis=${encodeURIComponent(DEMO_ANALYSIS)}`;
    const payload = {
      audioUrl: DEMO_AUDIO,
      analysisUrl: DEMO_ANALYSIS,
      viewerUrl
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "audio-annotator-mcp",
  title: "Audio Annotator",
  version: "0.1.0",
  instructions: "Tools for the Audio Annotator app \u2014 a formal music-analysis viewer. Use `get_demo` for a built-in example, `build_viewer_url` to construct a shareable read-only viewer link from an audio URL (and optional analysis JSON URL), and `fetch_analysis_summary` to inspect an analysis JSON's sections and VCU groups.",
  tools: [get_demo_default, build_viewer_url_default, fetch_analysis_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
